name: daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        run: |
          docker --version
          docker compose --version
      - name: Build docker cache
        run: |
          make fresh-cache
      - name: Push docker cache (hash)
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
          docker push ghcr.io/${{ github.repository }}:cache
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
